export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)
# eval "$(/opt/homebrew/bin/brew shellenv)
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"


